In [1]:
import pandas as pd
import numpy as np

np.set_printoptions(precision=2)

In [2]:
x1 = np.random.rand(2,5)*10
x1

array([[2.76, 7.41, 6.8 , 7.06, 5.07],
       [4.71, 0.98, 1.4 , 7.68, 0.56]])

In [3]:
x2 = np.random.rand(2,5)*10
x2

array([[0.58, 3.02, 8.69, 3.69, 6.83],
       [1.38, 0.27, 5.21, 0.72, 0.8 ]])

# Concatencacion con Numpy

In [4]:
np.concatenate([x1,x2], axis=1)

array([[2.76, 7.41, 6.8 , 7.06, 5.07, 0.58, 3.02, 8.69, 3.69, 6.83],
       [4.71, 0.98, 1.4 , 7.68, 0.56, 1.38, 0.27, 5.21, 0.72, 0.8 ]])

# Concatenacion con Pandas

In [5]:
s1 = pd.Series(x1[0],index=['a','b','c','d','e'])
s1

a    2.764890
b    7.408717
c    6.795911
d    7.064030
e    5.070932
dtype: float64

In [8]:
s2 = pd.Series(x2[0], index=['c','b','e','f','g'])
s2

c    0.581020
b    3.016793
e    8.686765
f    3.686395
g    6.827822
dtype: float64

## Resetear indices

In [48]:
s1 = s1.reset_index(drop=True)
s2 = s2.reset_index(drop=True)

In [51]:
con = pd.concat([s1,s2], axis=1)
con

0         1
0  2.764890  0.581020
1  7.408717  3.016793
2  6.795911  8.686765
3  7.064030  3.686395
4  5.070932  6.827822

## Concatenar DataFrames

In [52]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a         b
0  0.531147  2.206365
1  1.273444  0.584015
2  7.619771  5.597232

In [53]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index=[2,3,4])
df2

a         b
2 -0.917823 -0.342608
3 -0.500029 -0.033491
4 -0.456622 -0.163551

In [55]:
pd.concat([df1,df2], axis=1)

a         b         a         b
0  0.531147  2.206365       NaN       NaN
1  1.273444  0.584015       NaN       NaN
2  7.619771  5.597232 -0.917823 -0.342608
3       NaN       NaN -0.500029 -0.033491
4       NaN       NaN -0.456622 -0.163551

## Guardar solo los indices que comparten los DataFrames

In [56]:
pd.concat([df1,df2], axis=1, join='inner')

a         b         a         b
2  7.619771  5.597232 -0.917823 -0.342608

In [58]:
pd.concat([
    df1.reset_index(drop=True),
    df2.reset_index(drop=True)
], axis=1)

a         b         a         b
0  0.531147  2.206365 -0.917823 -0.342608
1  1.273444  0.584015 -0.500029 -0.033491
2  7.619771  5.597232 -0.456622 -0.163551

## Append : Se puede pegar multiples DataFrames

In [60]:
df1.append(df2).append(df1)

a         b
0  0.531147  2.206365
1  1.273444  0.584015
2  7.619771  5.597232
2 -0.917823 -0.342608
3 -0.500029 -0.033491
4 -0.456622 -0.163551
0  0.531147  2.206365
1  1.273444  0.584015
2  7.619771  5.597232

Append a lo largo de los ejes de las **columnas** debemos usar las Traspuesta del DataFrame.

In [61]:
df1.T.append(df2.T).T

a         b         a         b
0  0.531147  2.206365       NaN       NaN
1  1.273444  0.584015       NaN       NaN
2  7.619771  5.597232 -0.917823 -0.342608
3       NaN       NaN -0.500029 -0.033491
4       NaN       NaN -0.456622 -0.163551

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=40d7a071-7e6a-4668-9914-a7e81441c111' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>